### ISSUE TITLE
about pytorch parallel error

### ISSUE THREAD

**Issue by zhangzhenyu-zzy** [microsoft/MeshTransformer#26]
**when i training it in this code:**
python -m torch.distributed.launch --nproc_per_node=8 \
       metro/tools/run_metro_bodymesh.py \
       --train_yaml Tax-H36m-coco40k-Muco-UP-Mpii/train.yaml \
       --val_yaml human3.6m/valid.protocol2.yaml \
       --arch hrnet-w64 \
       --num_workers 4 \
       --per_gpu_train_batch_size 30 \
       --per_gpu_eval_batch_size 30 \
       --num_hidden_layers 4 \
       --num_attention_heads 4 \
       --lr 1e-4 \
       --num_train_epochs 200 \
       --input_feat_dim 2051,512,128 \
       --hidden_feat_dim 1024,256,128 

**then it will happen error like that:**

=======================================
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
Traceback (most recent call last):
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
    main(args)
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
Traceback (most recent call last):
    main(args)
    main(args)
    main(args)
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
Traceback (most recent call last):
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
    main(args)
    main(args)
  File "metro/tools/run_metro_bodymesh.py", line 714, in <module>
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    main(args)
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
    main(args)
  File "metro/tools/run_metro_bodymesh.py", line 587, in main
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    print("Init distributed training on local rank {} ({}), rank {}, world size {}".format(args.local_rank, int(os.environ["LOCAL_RANK"]), int(os.environ["NODE_RANK"]), args.num_gpus))
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
    raise KeyError(key) from None
    raise KeyError(key) from None
    raise KeyError(key) from None
    raise KeyError(key) from None
    raise KeyError(key) from None
    raise KeyError(key) from None
KeyError: 'NODE_RANK'
    raise KeyError(key) from None
KeyError: 'NODE_RANK'
KeyError: 'NODE_RANK'
KeyError: 'NODE_RANK'
KeyError: 'NODE_RANK'
KeyError: 'NODE_RANK'
KeyError: 'NODE_RANK'
KeyError: 'NODE_RANK'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
**subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', 'metro/tools/run_metro_bodymesh.py', '--local_rank=7', '--train_yaml', 'Tax-H36m-coco40k-Muco-UP-Mpii/train.yaml', '--val_yaml', 'human3.6m/valid.protocol2.yaml', '--arch', 'hrnet-w64', '--num_workers', '4', '--per_gpu_train_batch_size', '30', '--per_gpu_eval_batch_size', '30', '--num_hidden_layers', '4', '--num_attention_heads', '4', '--lr', '1e-4', '--num_train_epochs', '200', '--input_feat_dim', '2051,512,128', '--hidden_feat_dim', '1024,256,128']' returned non-zero exit status 1.****
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

**how can i deal with it?**

**Comment by kevinlin311tw** [comment]
Could you share more info about your dev machine? Can you print out your environment variables?

**Comment by uyoung-jeong** [comment]
I got the same error, but the cause might be different. In my case, setting `nproc_per_node=1` runs the code without an error. However, running with more than 1 process raises KeyError: 'NODE_RANK'. There would be some problem while running distributed process.
