### ISSUE TITLE
what is modeling_bert.py?

### ISSUE THREAD

**Issue by khw11044** [microsoft/MeshTransformer#59]
python3 ./metro/tools/end2end_inference_bodymesh.py --resume_checkpoint ./models/metro_release/metro_3dpw_state_dict.bin--image_file_or_path ./samples/human-body

Traceback (most recent call last):
  File "./metro/tools/end2end_inference_bodymesh.py", line 20, in <module>
    from metro.modeling.bert import BertConfig, METRO
  File "/media/khw/T7/3DHuman/MeshTransformer/metro/modeling/bert/__init__.py", line 3, in <module>
    from .modeling_bert import (BertConfig, BertModel,
  File "/media/khw/T7/3DHuman/MeshTransformer/metro/modeling/bert/modeling_bert.py", line 1
    ../../../transformers/pytorch_transformers/modeling_bert.py
    ^
SyntaxError: invalid syntax

how can i fix it?
what should i do now?

**Comment by kevinlin311tw** [comment]
We use a symbolic link to reference the official codes in Huggingface's transformer. Please have a check if you clone the repo. You could try running `git clone --recursive https://github.com/microsoft/MeshTransformer.git` and it should clone Huggingface's transformer submodule automatically. Thanks.

**Comment by luckyday2022** [comment]
> 

How did you solve the problem?
